export const categoryOptions = [
    "Web Development",
    "Mobile App Development",
    "Database Management",
    "Cloud Computing",
    "Network Infrastructure",
    "Cybersecurity",
    "Data Analytics",
    "Artificial Intelligence (AI)",
    "Machine Learning",
    "Internet of Things (IoT)",
    "DevOps",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Software Testing",
    "Hardware Development",
    "Embedded Systems",
    "Robotics",
    "Data Science",
    "Blockchain",
    "3D Printing",
    "Renewable Energy",
    "Aerospace Engineering",
    "Biotechnology",
    "Healthcare Technology",
    "Automotive Technology"
];

export const instituteOptions = [
    "Gujarat University",
    "Sardar Patel University",
    "Maharaja Sayajirao University of Baroda",
    "Veer Narmad South Gujarat University",
    "Bhavnagar University",
    "Kachchh University",
    "Hemchandracharya North Gujarat University",
    "Dharmsinh Desai University",
    "Gujarat Technological University",
    "Saurashtra University",
    "Ganpat University",
    "Charotar University of Science and Technology",
    "Nirma University",
    "Pandit Deendayal Petroleum University",
    "Anand Agricultural University",
    "Gujarat Ayurved University",
    "Dr. Babasaheb Ambedkar Open University",
    "Sumandeep Vidyapeeth",
    "UKA Tarsadia University",
    "Navsari Agricultural University",
    "Gujarat National Law University",
    "CEPT University",
    "Raksha Shakti University",
    "Sardar Patel University of Police, Security and Criminal Justice",
    "GSFC University",
    "Institute of Infrastructure Technology Research and Management (IITRAM)",
    "Gujarat Maritime University",
    "National Institute of Design (NID), Gandhinagar",
    "Sardarkrushinagar Dantiwada Agricultural University",
    "Junagadh Agricultural University",
    "Gujarat Forensic Sciences University",
    "Maharaja Krishnakumarsinhji Bhavnagar University",
    "The MS University of Baroda - Maharaja Ranjitsingh Gaekwad Institute of Design (MRID)",
    "Indian Institute of Technology (IIT) Gandhinagar",
    "Indian Institute of Management (IIM) Ahmedabad",
    "Indian Institute of Technology (IIT) Ahmedabad",
    "CEPT University",
    "Nirma University of Science and Technology",
    "Gujarat Vidyapith",
    "Indus University"

]
